### ISSUE TITLE
Présence des CEDEX

### ISSUE THREAD

**Issue by MathRobin** [BaseAdresseNationale/codes-postaux#15]
La base de données n'inclue que les villes elles-même. Est-ce qu'il serait possible d'ajouter les cedex aussi dans le CSV ?

**Comment by jdesboeufs** [comment]
Hélas la base des CEDEX est un produit commercial de La Poste.
Nous pourrions néanmoins en reconstruire une base par assemblage d'autres données ouvertes (par exemple la base SIRENE) mais nous n'avons rien prévu de cet ordre pour le moment.
Toute contribution est bien sûr la bienvenue :)

**Comment by MattiSG** [comment]
Si cela n'est pas prévu pour le moment, je ferme cette _issue_. Ne pas hésiter à la rouvrir si ça devient un investissement actif.

**Comment by jdesboeufs** [comment]
Les données ont finalement été extraites : https://www.data.gouv.fr/fr/datasets/liste-des-cedex/
