### ISSUE TITLE
Mettre à jour les codes postaux avec fimoct janvier 2023

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/codes-postaux#44]
Mettre à jour les codes postaux avec la livraison de fimoct janvier 2023.
Documenter la production au passage.

**Comment by mmortier** [comment]
Le fichier FIMOCT de janvier est livré.

**Comment by antoineludeau** [comment]
La mise à jour des codes postaux avec FIMOCT de janvier 2023 a été faite dans le version 4.0.0 du package "codes-postaux". Il faudra donc mettre à jour ban-plateforme (et toutes les autres briques qui utilise "codes-postaux") avec cette nouvelle version.

**Comment by antoineludeau** [comment]
La mise à jour des codes-postaux version 4.0.0 dans ban-plateforme sera faite avec la mise à jour du COG 2023 (https://github.com/orgs/BaseAdresseNationale/projects/4/views/22?pane=issue&itemId=20953486)
