### ISSUE TITLE
Trier les résultats par importance de la ville

### ISSUE THREAD

**Issue by MattiSG** [BaseAdresseNationale/codes-postaux#5]
@cquest Serait-il possible de trier le CSV par importance la ville (chef-lieu, nombre d'habitants…) comme dans la BANO ?  :)

**Comment by cquest** [comment]
Bien pratique pour l'autocomplétion... je peux sortir un CSV avec ce champ "importance" avec un calcul identique à celui fait dans BAN/BANO. Il se base sur le niveau administratif et la population.

**Comment by MattiSG** [comment]
Ce serait génial !

**Comment by guillett** [comment]
@jdesboeufs merci pour les évolutions récentes. L'ajout de la population te parait-il possible dans ce module ?

Je viens de regarder 5 minutes dans `/build` sans succès. :)

Merci.

**Comment by jdesboeufs** [comment]
Ce n'est pas le rôle de ce module.
Mais c'est ce qu'on fait avec https://github.com/etalab/decoupage-administratif, qui attend encore sa documentation et quelques helpers pour devenir un vrai module.

**Comment by jdesboeufs** [comment]
En l'état tu peux déjà faire `require('@etalab/decoupage-administratif/data/communes.json')` et indexer par codes postaux :)

**Comment by jdesboeufs** [comment]
Ou directement http://unpkg.com/@etalab/decoupage-administratif/data/communes.json

**Comment by guillett** [comment]
Cool, merci pour ta réactivité !
