### ISSUE TITLE
Code Postal 97150 inconnu

### ISSUE THREAD

**Issue by malakhi81** [BaseAdresseNationale/codes-postaux#51]
L'appel pour interrogation du code postal 97150 retourne une 404
https://www.le-codepostal.com/97150.html

**Comment by FrederiqWilliams** [comment]
Cette page d'information ne dépend pas de notre équipe

**Comment by malakhi81** [comment]
Je ne mentionnais cette page d'information que comme référence pour l'existence du code postal indiqué
La page retournant une 404 est bien celle de l'appel api de BaseAdresseNationale

**Comment by FrederiqWilliams** [comment]
ah désolé mal compris. 
Est-ce que votre message est toujours d'actualité? 
nous n'avons pas d'API signalé en défaut
