### ISSUE TITLE
Ajout d'un fichier publiccode.yml pour être promu via code.gouv.fr

### ISSUE THREAD

**Issue by bzg** [BaseAdresseNationale/codes-postaux#58]
Votre dépôt est référencé comme "Awesome" dans https://code.gouv.fr/fr/awesome/.

Pour ce référencement, la mission logiciels libres a créé un fichier `publiccode.yml` avec des metadonnées sur le dépôt, fichier que vous trouverez dans [ce répertoire](https://github.com/codegouvfr/awesome-codegouvfr/tree/main/dist).

D'ici octobre, nous mettrons à jour https://code.gouv.fr/sources et nous listerons les dépôt Awesome en allant chercher les métadonnées directement depuis un fichier publiccode.yml à la racine du dépôt.

Pourriez-vous rappatrier le `publiccode.yml` de [ce répertoire](https://github.com/codegouvfr/awesome-codegouvfr/tree/main/dist) et l'ajouter à votre dépôt ?

Si besoin, je peux proposer de faire la PR, vous me dites :)  Merci !

**Comment by FrederiqWilliams** [comment]
Bonjour, ça nous fait plaisir :) 
mais ça m'embête un peu que ce dépôt précisément soit ciblé, car ce produit code-postaux n'a pas été actualisé depuis longtemps et nous travaillons sur une nouvelle version de la mise à disposition de cette information. 
Je vois avec l'équipe technique ce qui est pertinent de vous mettre à disposition. 
à bientôt!

**Comment by bzg** [comment]
Merci pour votre réponse ! J'ai retiré ce dépôt de la liste "Awesome" - vous pourrez toujours demander de la rejoindre avec le nouveau dépôt plus tard.
